### ISSUE TITLE
Check references fails with `no such file or directory, scandir './qa-scenarios/'`

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/approbation#77]
## Issue

When running the approbation check for references it is failing with the following error `no such file or directory, scandir './qa-scenarios/'`

## Expected behaviour

The check references works correctly now that the feature-tests have moved from ./qa-scenarios/ to https://github.com/vegaprotocol/vega/tree/develop/core/integration/features/**

## Additional information

The full output is here:

```
gordonharradine@Gordon-Vega specs % make references
npx @vegaprotocol/approbation check-references
node:internal/fs/utils:346
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir './qa-scenarios/'
    at Object.readdirSync (node:fs:1437:3)
    at Object.<anonymous> (/Users/gordonharradine/.npm/_npx/4b2f3d100a9b8643/node_modules/@vegaprotocol/approbation/src/check-references.js:46:4)
    at Module._compile (node:internal/modules/cjs/loader:1239:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1293:10)
    at Module.load (node:internal/modules/cjs/loader:1096:32)
    at Module._load (node:internal/modules/cjs/loader:935:12)
    at Module.require (node:internal/modules/cjs/loader:1120:19)
    at require (node:internal/modules/helpers:112:18)
    at Object.<anonymous> (/Users/gordonharradine/.npm/_npx/4b2f3d100a9b8643/node_modules/@vegaprotocol/approbation/bin/approbation.js:10:5)
    at Module._compile (node:internal/modules/cjs/loader:1239:14) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: './qa-scenarios/'
}

Node.js v19.4.0
make: *** [references] Error 1
```

**Comment by gordsport** [comment]
Not an issue with approbation  - resolved in the specs repo make file.
